export const FETCH_TRANS_HISTORY = 'FETCH_TRANS_HISTORY';
export const FETCH_TRANS_HISTORY_SUCCEED = 'FETCH_TRANS_HISTORY_SUCCEED';
export const FETCH_TRANS_HISTORY_FAILED = 'FETCH_TRANS_HISTORY_FAILED';
