export const LOGIN_HISTORY = 'LOGIN_HISTORY';
export const LOGIN_HISTORY_FAILED = 'LOGIN_HISTORY_FAILED';
export const LOGIN_HISTORY_SUCCEED = 'LOGIN_HISTORY_SUCCEED';

export const USER_LIST = 'USER_LIST';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';
export const USER_LIST_SUCCEED = 'USER_LIST_SUCCEED';

export const USER_SEARCH =  'USER_SEARCH'

export const USER_INFO  = 'USER_INFO'
export const USER_INFO_SUCCEED = 'USER_INFO_SUCCEED'


export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';



