export const FETCH_ALL_ADMIN = 'FETCH_ALL_ADMIN';
export const FETCH_ALL_ADMIN_FAILED = 'FETCH_ALL_ADMIN_FAILED';
export const FETCH_ALL_ADMIN_SUCCEED = 'FETCH_ALL_ADMIN_SUCCEED';

export const ON_CREATE_ADMIN = 'ON_CREATE_ADMIN';
export const ON_CREATE_ADMIN_SUCCEED = 'ON_CREATE_ADMIN_SUCCEED';
export const ON_CREATE_ADMIN_FAILED = 'ON_CREATE_ADMIN_FAILED';

export const FETCH_ADMIN_LOGIN_HISTORY = 'FETCH_ADMIN_LOGIN_HISTORY';
export const FETCH_ADMIN_LOGIN_HISTORY_FAILED = 'FETCH_ADMIN_LOGIN_HISTORY_FAILED';
export const FETCH_ADMIN_LOGIN_HISTORY_SUCCEED = 'FETCH_ADMIN_LOGIN_HISTORY_SUCCEED';

export const FETCH_AUTH_INFO = 'FETCH_AUTH_INFO';
export const FETCH_AUTH_INFO_FAILED = 'FETCH_AUTH_INFO_FAILED';
export const FETCH_AUTH_INFO_SUCCEED = 'FETCH_AUTH_INFO_SUCCEED';

export const GET_ROLE_BY_PUBKEY = 'GET_ROLE_BY_PUBKEY';
export const POST_ROLE_FOR_USER = 'POST_ROLE_FOR_USER';


// users
export const GET_AUTHOR_INFO_FOR_USER = 'GET_AUTHOR_INFO_FOR_USER';
export const GET_AUTHOR_INFO_FOR_USER_SUCCESS = 'GET_AUTHOR_INFO_FOR_USER_SUCCESS';