
export const FETCH_PRODUCTS_ACTION = "FETCH_PRODUCTS_ACTION"
export const FETCH_PRODUCTS_ACTION_SUCCEED = "FETCH_PRODUCTS_ACTION_SUCCEED"

export const FETCH_PRODUCT_SEARCH =  'FETCH_PRODUCT_SEARCH'


export const FETCH_PRODUCTS_TYPE_ACTION = "FETCH_PRODUCTS_TYPE_ACTION"
export const FETCH_PRODUCTS_TYPE_ACTION_SUCCEED = "FETCH_PRODUCTS_TYPE_ACTION_SUCCEED"

export const FETCH_PRODUCTS_TYPE_INFO_ACTION = "FETCH_PRODUCTS_TYPE_INFO_ACTION"
