export const FETCH_FILTER_ORDER_HISTORY = 'FETCH_FILTER_ORDER_HISTORY';
export const FETCH_FILTER_ORDER_HISTORY_SUCCEED = 'FETCH_FILTER_ORDER_HISTORY_SUCCEED';
export const FETCH_FILTER_ORDER_HISTORY_FAILED = 'FETCH_FILTER_ORDER_HISTORY_FAILED';

export const FETCH_PAIRS_ORDER_HISTORY = 'FETCH_PAIRS_ORDER_HISTORY';
export const FETCH_PAIRS_ORDER_HISTORY_SUCCEED = 'FETCH_PAIRS_ORDER_HISTORY_SUCCEED';
export const FETCH_PAIRS_ORDER_HISTORY_FAILED = 'FETCH_PAIRS_ORDER_HISTORY_FAILED';
